server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/instapp-service
    default-schema: instapp
    password: postgres
    username: postgres
logging:
  level:
    -
      org:
        spring: DEBUG
